CREATE TABLE `rc_job_closure_approvals` (
  `id` int NOT NULL AUTO_INCREMENT,
  `job_listing_id` int NOT NULL,
  `selected_candidate_id` int DEFAULT NULL,
  `replacement_of_employee_id` int DEFAULT NULL,
  `hr_assessment_notes` text,
  `hr_approved_by` int DEFAULT NULL,
  `hr_approved_at` datetime DEFAULT NULL,
  `team_strengths` text,
  `team_weaknesses` text,
  `keep_posting_open` enum('yes','no') DEFAULT NULL,
  `keep_posting_reason` text,
  `current_team_size` int DEFAULT NULL,
  `best_performer_id` int DEFAULT NULL,
  `worst_performer_id` int DEFAULT NULL,
  `need_replacement` enum('yes','no') DEFAULT NULL,
  `replacement_details` text,
  `manager_comments` text,
  `manager_approved_by` int DEFAULT NULL,
  `manager_approved_at` datetime DEFAULT NULL,
  `current_step` enum('hr_approval','manager_feedback') CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT 'hr_approval',
  `final_closure_date` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_job_listing_id` (`job_listing_id`),
  KEY `idx_selected_candidate` (`selected_candidate_id`),
  KEY `idx_replacement_employee` (`replacement_of_employee_id`),
  KEY `idx_best_performer` (`best_performer_id`),
  KEY `idx_worst_performer` (`worst_performer_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb3